apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceaccount }}-kubedog-clusterrolebinding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: kubedog-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceaccount }}
    namespace: {{ .Values.namespace }}
