apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceaccount }}-cert-control-rolebinding
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cert-control-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceaccount }}
    namespace: {{ .Values.octopod_namespace | default .Values.namespace }}
