name: octo CLI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  macOS:
    name: Create macOS octo CLI Release (Stack)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache stack dependencies
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: octo-cli-stack-${{ runner.os }}
      # TODO: Remove this step once https://github.com/actions/cache/issues/445 is resolved.
      - name: Fix macOS cache bug
        run: rm -rf ~/.stack/setup-exe-cache
      - name: Build
        run: stack build octo-cli --local-bin-path out --copy-bins
      - uses: actions/upload-artifact@v2
        with:
          name: octo-cli-macos
          path: out/octo
  linux:
    name: Create Linux octo CLI Release (Nix)
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: octopod
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: Build
        run: nix-build nix/octo.nix
      - uses: actions/upload-artifact@v2
        with:
          name: octo-cli-linux
          path: result/bin/octo
  release:
    name: "Release"
    if: github.ref == 'refs/heads/master'
    runs-on: "ubuntu-latest"
    needs: [macOS, linux]
    steps:
      - uses: actions/download-artifact@v2
      - name: Zip
        run: |
          chmod +x octo-cli-macos/octo
          zip octo-cli-macos octo-cli-macos/octo
          chmod +x octo-cli-linux/octo
          zip octo-cli-linux octo-cli-linux/octo
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Pre-Release"
          files: |
            *.zip
